objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Organization</fullName>
        <active>true</active>
        <description>An Account representing an organization</description>
        <label>Organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GAU_Allocation_Change_Log__c.object
<CustomObject>
    <description>This object tracks all changes (Create / Edit / Delete) on the GAU Allocation object. The records are generated by an AfterTrigger on the GAU Allocation object. The object allows VSA to audit whenever a user or a system modifies the GAU allocations on an opportunity or a campaign record (VSA-43).</description>
    <fields>
        <fullName>Action__c</fullName>
        <description>This field contains a value of either &quot;Created | Edited | Deleted&quot;. The value in this field reflects whether the GAU allocation change log record itself is the result of a GAU allocation record being created, edited, or deleted. The field&apos;s value is set by the GAU Allocation trigger (VSA-43).</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Edited</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains a look-up to the campaign record which generated the GAU allocation change log. A GAU allocation change log record will either have a value in this field or in the Opportunity field - never in both (VSA-43).</description>
        <inlineHelpText>The campaign to which the GAU allocation change is linked.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>GAU Allocation Change Logs</relationshipLabel>
        <relationshipName>GAU_Allocation_Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_GAU_Allocation__c</fullName>
        <description>This field contains a text string which expresses the nature of the GAU allocation change. Please note that the &apos;£&apos;-sign in the text string is hard-coded because VSA is currently not supporting multi-currencies (VSA-43).</description>
        <inlineHelpText>The GAU Allocation change operation.</inlineHelpText>
        <label>New GAU Allocation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains a look-up to the opportunity record which generated the GAU allocation change log. A GAU allocation change log record will either have a value in this field or in the Campaign field - never in both (VSA-43).</description>
        <inlineHelpText>The opportunity to which the GAU allocation change is linked.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>GAU Allocation Change Logs</relationshipLabel>
        <relationshipName>GAU_Allocation_Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field contains a look-up to the user who made the GAU allocation change (VSA-43).</description>
        <inlineHelpText>The user who made the GAU Allocation change.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GAU_Allocation_Change_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GAU Allocation Change Log</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>GAU Allocation Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GAU Allocation Change Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllocationTriggerHandler_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AllocationTriggerHandler_Test {

    static testMethod void testLogCreation() {
    	
    	
    	list<npsp__Allocation__c> newgaus = new list<npsp__Allocation__c>();
    	
		// Create an Account that Donations can be linked to
		Account testAccount = TestFactory.createAccount('Test Account');
		insert testAccount;

        //Create Contact
         Contact con = new Contact (firstname = 'john', lastname = 'test', AccountId = testAccount.id, Email = 'test@test.com');
    	 Insert con;
    	    	
    	Campaign testCampaign = TestFactory.createCampaign(); 
    	
    	insert testCampaign;
    	
    	list<npsp__General_Accounting_Unit__c> newGenAllocs = new list<npsp__General_Accounting_Unit__c>();
    	
    	List<Opportunity> opps = new List<Opportunity>();

    	npsp__General_Accounting_Unit__c newGenAccUnit = new npsp__General_Accounting_Unit__c();
    	newGenAccUnit.name = 'test';
		newGenAllocs.add(newGenAccUnit);
    	
    	for (integer i = 0; i<100;i++) {
    		
    		Opportunity newOpp = TestFactory.createDonation(testCampaign, Date.today().addDays(i), testAccount.id, con.Id, 'Paid');
    		newOpp.amount = 100 + 1;
    		opps.add(newOpp);

	    	newGenAccUnit = new npsp__General_Accounting_Unit__c();
	    	newGenAccUnit.name = 'test'  + i;
    		newGenAllocs.add(newGenAccUnit);
    	

    	}
    	
    	insert newGenAllocs;
    	
		insert opps;        

    	for (integer i = 0; i<100;i++) {
    		
    		npsp__Allocation__c newGAU = new npsp__Allocation__c();
    		
    		newGAU.npsp__Amount__c = opps[i].amount- (opps[i].amount/100) * i;
    		newGAU.npsp__Percent__c = 100-i;
    		newGAU.npsp__Opportunity__c = opps[i].id;
    		newGAU.npsp__General_Accounting_Unit__c = newGenAllocs[i].id;
    		
    		newgaus.add(newGAU);

    		newGAU = new npsp__Allocation__c();
    		
    		newGAU.npsp__Amount__c = (opps[i].amount/100) * i;
    		newGAU.npsp__Percent__c = i;
    		newGAU.npsp__Opportunity__c = opps[i].id;
    		newGAU.npsp__General_Accounting_Unit__c = newGenAllocs[i+1].id;
    		
    		newgaus.add(newGAU);
    	}
    	
		insert newgaus;        

		List<GAU_Allocation_Change_Log__c> logs = [select id, New_GAU_Allocation__c, Opportunity__c, Campaign__c, Action__c, User__c from GAU_Allocation_Change_Log__c];

		system.assertEquals(logs.size(), 200);
		
		map<string, GAU_Allocation_Change_Log__c> logMap = new map<string, GAU_Allocation_Change_Log__c>();
		
		for (GAU_Allocation_Change_Log__c log:logs) {
			system.debug('log.New_GAU_Allocation__c - <' + log.New_GAU_Allocation__c +'>');
			logMap.put(log.New_GAU_Allocation__c, log);
				
		}
		
		map<id,  npsp__General_Accounting_Unit__c> GAUMap = new map<id,  npsp__General_Accounting_Unit__c>([select id, name from npsp__General_Accounting_Unit__c]);
		
		for (npsp__Allocation__c newgau:newgaus) {

    		string amount = string.valueOf(newgau.npsp__Amount__c);	
    		string percentage = string.valueOf(newgau.npsp__Percent__c.format());	

			npsp__General_Accounting_Unit__c gau = GAUMap.get(newgau.npsp__General_Accounting_Unit__c);

			system.debug('gau - <' + gau +'>');
				
			string gauName = gau.name;
			
			string keyVal = gauName + ' (£' + amount +' / ' + percentage + '%)';

			system.debug('keyVal - <' + keyVal +'>');
			
			GAU_Allocation_Change_Log__c thisLog = logMap.get(keyVal);
			
			system.assertEquals(thisLog.Opportunity__c, newgau.npsp__Opportunity__c);
			system.assertEquals(thisLog.Campaign__c, null);
			system.assertEquals(thisLog.Action__c, 'Created');
			
			system.assertEquals(thisLog.User__c, UserInfo.getUserId());
			
		}
    }
    
    static testMethod void testLogUpdate() {
    	
    	
    	list<npsp__Allocation__c> newgaus = new list<npsp__Allocation__c>();
    	
		// Create an Account that Donations can be linked to
		Account testAccount = TestFactory.createAccount('Test Account');
		insert testAccount;

        //Create Contact
         Contact con = new Contact (firstname = 'john', lastname = 'test', AccountId = testAccount.id, Email = 'test@test.com');
    	 Insert con;
    	    	
    	Campaign testCampaign = TestFactory.createCampaign(); 
    	
    	insert testCampaign;
    	
    	list<npsp__General_Accounting_Unit__c> newGenAllocs = new list<npsp__General_Accounting_Unit__c>();
    	
    	List<Opportunity> opps = new List<Opportunity>();

    	npsp__General_Accounting_Unit__c newGenAccUnit = new npsp__General_Accounting_Unit__c();
    	newGenAccUnit.name = 'test';
		newGenAllocs.add(newGenAccUnit);
    	
    	for (integer i = 0; i<100;i++) {
    		
    		Opportunity newOpp = TestFactory.createDonation(testCampaign, Date.today().addDays(i), testAccount.id, con.Id, 'Paid');
    		newOpp.amount = 100 + 1;
    		opps.add(newOpp);

	    	newGenAccUnit = new npsp__General_Accounting_Unit__c();
	    	newGenAccUnit.name = 'test'  + i;
    		newGenAllocs.add(newGenAccUnit);
    	

    	}
    	
    	insert newGenAllocs;
    	
		insert opps;        

    	for (integer i = 0; i<100;i++) {
    		
    		npsp__Allocation__c newGAU = new npsp__Allocation__c();
    		
    		newGAU.npsp__Amount__c = opps[i].amount- (opps[i].amount/100) * i;
    		newGAU.npsp__Percent__c = 100-i;
    		newGAU.npsp__Opportunity__c = opps[i].id;
    		newGAU.npsp__General_Accounting_Unit__c = newGenAllocs[i].id;
    		
    		newgaus.add(newGAU);

    		newGAU = new npsp__Allocation__c();
    		
    		newGAU.npsp__Amount__c = (opps[i].amount/100) * i;
    		newGAU.npsp__Percent__c = i;
    		newGAU.npsp__Opportunity__c = opps[i].id;
    		newGAU.npsp__General_Accounting_Unit__c = newGenAllocs[i+1].id;
    		
    		newgaus.add(newGAU);
    	}
    	
		insert newgaus;        

		List<GAU_Allocation_Change_Log__c> logs = [select id, New_GAU_Allocation__c, Opportunity__c, Campaign__c, Action__c, User__c from GAU_Allocation_Change_Log__c];

		system.assertEquals(logs.size(), 200);
		
		map<string, GAU_Allocation_Change_Log__c> logMap = new map<string, GAU_Allocation_Change_Log__c>();
		
		for (GAU_Allocation_Change_Log__c log:logs) {
//			system.debug('log.New_GAU_Allocation__c - <' + log.New_GAU_Allocation__c +'>');
			logMap.put(log.New_GAU_Allocation__c, log);
				
		}
		
		map<id,  npsp__General_Accounting_Unit__c> GAUMap = new map<id,  npsp__General_Accounting_Unit__c>([select id, name from npsp__General_Accounting_Unit__c]);
		
		for (npsp__Allocation__c newgau:newgaus) {

    		string amount = string.valueOf(newgau.npsp__Amount__c);	
    		string percentage = string.valueOf(newgau.npsp__Percent__c.format());	

			npsp__General_Accounting_Unit__c gau = GAUMap.get(newgau.npsp__General_Accounting_Unit__c);

	//		system.debug('gau - <' + gau +'>');
				
			string gauName = gau.name;
			
			string keyVal = gauName + ' (£' + amount +' / ' + percentage + '%)';

//			system.debug('keyVal - <' + keyVal +'>');
			
			GAU_Allocation_Change_Log__c thisLog = logMap.get(keyVal);
			
			system.assertEquals(thisLog.Opportunity__c, newgau.npsp__Opportunity__c);
			system.assertEquals(thisLog.Campaign__c, null);
			system.assertEquals(thisLog.Action__c, 'Created');
			
			system.assertEquals(thisLog.User__c, UserInfo.getUserId());
			
		}
		
		delete logs;
		
		list<npsp__Allocation__c> updatedGaus = new list<npsp__Allocation__c>();
				
    	decimal total = newgaus[4].npsp__Amount__c + newgaus[5].npsp__Amount__c;

		system.debug('total - <' + total +'>');
		system.debug('newgaus[5].npsp__Amount__c - <' + newgaus[5].npsp__Amount__c +'>');
		system.debug('newgaus[5].npsp__Percent__c - <' + newgaus[5].npsp__Percent__c +'>');
		system.debug('newgaus[4].npsp__Amount__c - <' + newgaus[4].npsp__Amount__c +'>');
		system.debug('newgaus[4].npsp__Percent__c - <' + newgaus[4].npsp__Percent__c +'>');
		system.debug('(total *5/100) - <' + (total *5/100) +'>');
    		
    	newgaus[5].npsp__Amount__c = newgaus[5].npsp__Amount__c + (total *5/100);
    		
    	newgaus[4].npsp__Amount__c = newgaus[4].npsp__Amount__c - (total *5/100);

    	newgaus[5].npsp__Percent__c = newgaus[5].npsp__Percent__c + 5;
    		
    	newgaus[4].npsp__Percent__c= newgaus[4].npsp__Percent__c - 5;

		system.debug('newgaus[5].npsp__Amount__c - <' + newgaus[5].npsp__Amount__c +'>');
		system.debug('newgaus[5].npsp__Percent__c - <' + newgaus[5].npsp__Percent__c +'>');
		system.debug('newgaus[4].npsp__Amount__c - <' + newgaus[4].npsp__Amount__c +'>');
		system.debug('newgaus[4].npsp__Percent__c - <' + newgaus[4].npsp__Percent__c +'>');
    	
    	updatedGaus.add(newgaus[4]);
    	updatedGaus.add(newgaus[5]);
    	
		update updatedGaus;  				

		logs = [select id, New_GAU_Allocation__c, Opportunity__c, Campaign__c, Action__c, User__c from GAU_Allocation_Change_Log__c];

		system.assertEquals(logs.size(), 2);
		
		logMap = new map<string, GAU_Allocation_Change_Log__c>();
		
		for (GAU_Allocation_Change_Log__c log:logs) {
			system.debug('log.New_GAU_Allocation__c - <' + log.New_GAU_Allocation__c +'>');
			logMap.put(log.New_GAU_Allocation__c, log);
				
		}

		GAUMap = new map<id,  npsp__General_Accounting_Unit__c>([select id, name from npsp__General_Accounting_Unit__c]);
		
		for (npsp__Allocation__c newgau:updatedGaus) {

    		string amount = string.valueOf(newgau.npsp__Amount__c);	
    		string percentage = string.valueOf(newgau.npsp__Percent__c.format());	

			npsp__General_Accounting_Unit__c gau = GAUMap.get(newgau.npsp__General_Accounting_Unit__c);

			system.debug('gau - <' + gau +'>');
				
			string gauName = gau.name;
			
			string keyVal = gauName + ' (£' + amount +' / ' + percentage + '%)';

			system.debug('keyVal - <' + keyVal +'>');
			
			GAU_Allocation_Change_Log__c thisLog = logMap.get(keyVal);
			
			system.assertEquals(thisLog.Opportunity__c, newgau.npsp__Opportunity__c);
			system.assertEquals(thisLog.Campaign__c, null);
			system.assertEquals(thisLog.Action__c, 'Edited');
			
			system.assertEquals(thisLog.User__c, UserInfo.getUserId());
			
		}
    }

    static testMethod void testLogDelete() {
    		
    	list<npsp__Allocation__c> newgaus = new list<npsp__Allocation__c>();
    	
		// Create an Account that Donations can be linked to
		Account testAccount = TestFactory.createAccount('Test Account');
		insert testAccount;

        //Create Contact
         Contact con = new Contact (firstname = 'john', lastname = 'test', AccountId = testAccount.id, Email = 'test@test.com');
    	 Insert con;
    	    	
    	Campaign testCampaign = TestFactory.createCampaign(); 
    	
    	insert testCampaign;
    	
    	list<npsp__General_Accounting_Unit__c> newGenAllocs = new list<npsp__General_Accounting_Unit__c>();
    	
    	List<Opportunity> opps = new List<Opportunity>();

    	npsp__General_Accounting_Unit__c newGenAccUnit = new npsp__General_Accounting_Unit__c();
    	newGenAccUnit.name = 'test';
		newGenAllocs.add(newGenAccUnit);
    	
    	for (integer i = 0; i<100;i++) {
    		
    		Opportunity newOpp = TestFactory.createDonation(testCampaign, Date.today().addDays(i), testAccount.id, con.Id, 'Paid');
    		newOpp.amount = 100 + 1;
    		opps.add(newOpp);

	    	newGenAccUnit = new npsp__General_Accounting_Unit__c();
	    	newGenAccUnit.name = 'test'  + i;
    		newGenAllocs.add(newGenAccUnit);
    	

    	}
    	
    	insert newGenAllocs;
    	
		insert opps;        

    	for (integer i = 0; i<100;i++) {
    		
    		npsp__Allocation__c newGAU = new npsp__Allocation__c();
    		
    		newGAU.npsp__Amount__c = opps[i].amount- (opps[i].amount/100) * i;
    		newGAU.npsp__Percent__c = 100-i;
    		newGAU.npsp__Opportunity__c = opps[i].id;
    		newGAU.npsp__General_Accounting_Unit__c = newGenAllocs[i].id;
    		
    		newgaus.add(newGAU);

    		newGAU = new npsp__Allocation__c();
    		
    		newGAU.npsp__Amount__c = (opps[i].amount/100) * i;
    		newGAU.npsp__Percent__c = i;
    		newGAU.npsp__Opportunity__c = opps[i].id;
    		newGAU.npsp__General_Accounting_Unit__c = newGenAllocs[i+1].id;
    		
    		newgaus.add(newGAU);
    	}
    	
		insert newgaus;        

		List<GAU_Allocation_Change_Log__c> logs = [select id, New_GAU_Allocation__c, Opportunity__c, Campaign__c, Action__c, User__c from GAU_Allocation_Change_Log__c];

		system.assertEquals(logs.size(), 200);
		
		map<string, GAU_Allocation_Change_Log__c> logMap = new map<string, GAU_Allocation_Change_Log__c>();
		
		for (GAU_Allocation_Change_Log__c log:logs) {
//			system.debug('log.New_GAU_Allocation__c - <' + log.New_GAU_Allocation__c +'>');
			logMap.put(log.New_GAU_Allocation__c, log);
				
		}
		
		map<id,  npsp__General_Accounting_Unit__c> GAUMap = new map<id,  npsp__General_Accounting_Unit__c>([select id, name from npsp__General_Accounting_Unit__c]);
		
		for (npsp__Allocation__c newgau:newgaus) {

    		string amount = string.valueOf(newgau.npsp__Amount__c);	
    		string percentage = string.valueOf(newgau.npsp__Percent__c.format());	

			npsp__General_Accounting_Unit__c gau = GAUMap.get(newgau.npsp__General_Accounting_Unit__c);

	//		system.debug('gau - <' + gau +'>');
				
			string gauName = gau.name;
			
			string keyVal = gauName + ' (£' + amount +' / ' + percentage + '%)';

//			system.debug('keyVal - <' + keyVal +'>');
			
			GAU_Allocation_Change_Log__c thisLog = logMap.get(keyVal);
			
			system.assertEquals(thisLog.Opportunity__c, newgau.npsp__Opportunity__c);
			system.assertEquals(thisLog.Campaign__c, null);
			system.assertEquals(thisLog.Action__c, 'Created');
			
			system.assertEquals(thisLog.User__c, UserInfo.getUserId());
			
		}
		
		delete logs;
		
		list<npsp__Allocation__c> updatedGaus = new list<npsp__Allocation__c>();
				
    	decimal total = newgaus[4].npsp__Amount__c + newgaus[5].npsp__Amount__c;

		system.debug('total - <' + total +'>');
		system.debug('newgaus[5].npsp__Amount__c - <' + newgaus[5].npsp__Amount__c +'>');
		system.debug('newgaus[5].npsp__Percent__c - <' + newgaus[5].npsp__Percent__c +'>');
		system.debug('newgaus[4].npsp__Amount__c - <' + newgaus[4].npsp__Amount__c +'>');
		system.debug('newgaus[4].npsp__Percent__c - <' + newgaus[4].npsp__Percent__c +'>');
		system.debug('(total *5/100) - <' + (total *5/100) +'>');
    		
    	newgaus[5].npsp__Amount__c = newgaus[5].npsp__Amount__c + (total *5/100);
    		
    	newgaus[4].npsp__Amount__c = newgaus[4].npsp__Amount__c - (total *5/100);

    	newgaus[5].npsp__Percent__c = newgaus[5].npsp__Percent__c + 5;
    		
    	newgaus[4].npsp__Percent__c= newgaus[4].npsp__Percent__c - 5;

		system.debug('newgaus[5].npsp__Amount__c - <' + newgaus[5].npsp__Amount__c +'>');
		system.debug('newgaus[5].npsp__Percent__c - <' + newgaus[5].npsp__Percent__c +'>');
		system.debug('newgaus[4].npsp__Amount__c - <' + newgaus[4].npsp__Amount__c +'>');
		system.debug('newgaus[4].npsp__Percent__c - <' + newgaus[4].npsp__Percent__c +'>');
    	
    	updatedGaus.add(newgaus[4]);
    	updatedGaus.add(newgaus[5]);
    	
		delete updatedGaus;  				

		logs = [select id, New_GAU_Allocation__c, Opportunity__c, Campaign__c, Action__c, User__c from GAU_Allocation_Change_Log__c];

		system.assertEquals(logs.size(), 2);
		
		logMap = new map<string, GAU_Allocation_Change_Log__c>();
		
		for (GAU_Allocation_Change_Log__c log:logs) {
			system.debug('log.New_GAU_Allocation__c - <' + log.New_GAU_Allocation__c +'>');
			logMap.put(log.New_GAU_Allocation__c, log);
				
		}

		GAUMap = new map<id,  npsp__General_Accounting_Unit__c>([select id, name from npsp__General_Accounting_Unit__c]);

		updatedGaus = [select id, npsp__Amount__c, npsp__Percent__c, npsp__General_Accounting_Unit__c, npsp__Opportunity__c from npsp__Allocation__c where isDeleted = true ALL ROWS];

		system.assertEquals(updatedGaus.size(), 2);
		
		for (npsp__Allocation__c newgau:updatedGaus) {

    		string amount = string.valueOf(newgau.npsp__Amount__c);	
    		string percentage = string.valueOf(newgau.npsp__Percent__c.format());	

			npsp__General_Accounting_Unit__c gau = GAUMap.get(newgau.npsp__General_Accounting_Unit__c);

			system.debug('gau - <' + gau +'>');
				
			string gauName = gau.name;
			
			string keyVal = gauName + ' (Deleted)';

			system.debug('keyVal - <' + keyVal +'>');
			
			GAU_Allocation_Change_Log__c thisLog = logMap.get(keyVal);
			
			system.assertEquals(thisLog.Opportunity__c, newgau.npsp__Opportunity__c);
			system.assertEquals(thisLog.Campaign__c, null);
			system.assertEquals(thisLog.Action__c, 'Deleted');
			
			system.assertEquals(thisLog.User__c, UserInfo.getUserId());
			
		}
    }
           
}