objects/Export_to_Finance_Plugin__mdt.object
<CustomObject>
    <description>Export to Finance Plugins allow insertion of local Apex logic into the package logic</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>This field determines whether the Export to Finance Plugin is active. If unchecked, the logic will not run.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <inlineHelpText>The name of the Apex class which contains the plugin logic</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <inlineHelpText>The namespace for the Apex plugin code. Leave empty for local classes.</inlineHelpText>
        <label>Namespace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plugin_Key__c</fullName>
        <inlineHelpText>This field references the plugin key specified in the Export to Finance plugins class and drives at which point in the package the custom Apex logic will run.</inlineHelpText>
        <label>Plugin Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Export to Finance Plugin</label>
    <pluralLabel>Export to Finance Plugins</pluralLabel>
</CustomObject>

objects/Transaction_Export_Settings__mdt.object
<CustomObject>
    <description>Finance Export: This defines a transaction export. It defines which object should be grouped and how records should be grouped</description>
    <label>Transaction Export Settings</label>
    <pluralLabel>Transaction Export Settings</pluralLabel>
</CustomObject>

classes/PluginTest.cls
@isTest
public with sharing class PluginTest implements PluginTest.IPluginTest {

//	public static void addApplicationProperty(string logLevel) {

 //       	Clarity_Banking_Settings__c coreSettings = Clarity_Banking_Settings__c.getOrgDefaults();        

//	        coreSettings.Logging_Level__c = logLevel;
	        
//	        insert coreSettings;		

//	}
	
    /** IPluginTest **/
    // Define a plugin only to be used for test purposes
    public static final String PLUGIN_KEY_PLUGIN_TEST = 'IPluginTest';

    public static List<PluginTest.IPluginTest> getInstanceIPluginTest(Transaction_Export_Settings__mdt exportSettings){
        List<PluginTest.IPluginTest> plugins = new List<PluginTest.IPluginTest>();
  
        List<Object> pluginObjects = Plugin.getInstance(PLUGIN_KEY_PLUGIN_TEST, exportSettings);
        for(Object plugin : pluginObjects){ 
            plugins.add((PluginTest.IPluginTest) plugin);
        }

        return plugins;
    }

    public interface IPluginTest {
        Boolean pluginTest(Boolean result);
    }

    // Define a 'local' implementation of plugin
    public Boolean pluginTest(Boolean result){
        return result;
    } 
 
    /** GENERAL TEST METHODS **/
    private static testMethod void testInterfaceWithoutPlugins(){
   //     addApplicationProperty('DEBUG');
 		Transaction_Export_Settings__mdt exportSettings;

        Test.startTest();
        PluginTest.getInstanceIPluginTest(exportSettings);
        Test.stopTest();
 
//		Logger.flush();
//        List<Log__c> logs = [SELECT Message__c FROM Log__c];
//        System.assertEquals(1, logs.size());
//        System.assertEquals('No plugin found with key IPluginTest', logs[0].Message__c);
    }

    private static testMethod void testInterfaceWithIncorrectPlugin() {
        String plugins = '[{"' + 'Plugin_Key__c" : "IPluginTest", "'  + 'Namespace__c" : "", "' + 'Class__c" : "Fake", "'  + 'Active__c" : 1}]';
        Plugin.pluginList = (List<Export_to_Finance_Plugin__mdt>) JSON.deserialize(plugins, List<Export_to_Finance_Plugin__mdt>.class);
 		
 		Transaction_Export_Settings__mdt exportSettings;
 		system.debug('plugins - ' + plugins);
 
        Test.startTest();
        Boolean errorThrown = false;
        try {
            PluginTest.getInstanceIPluginTest(exportSettings);
        } catch(Plugin.PluginException e){ 
            errorThrown = true;
            System.assertEquals('Plugin with key \'IPluginTest\', namespace \'\' & class \'Fake\' not found', e.getMessage());
        }
        Test.stopTest();
        System.assert(errorThrown); 
    }
 
    private static testMethod void testInterfaceWithMultiplePlugins() {
        String plugins = '[';
        plugins = plugins + '{"'  + 'Plugin_Key__c" : "IPluginTest", "'  + 'Namespace__c" : "", "'  + 'Class__c" : "PluginTest", "'  + 'Active__c" : 1},';
        plugins = plugins + '{"'  + 'Plugin_Key__c" : "IPluginTest", "'  + 'Namespace__c" : "", "'  + 'Class__c" : "PluginTest", "'  + 'Active__c" : 1}';
        plugins = plugins + ']';
        Plugin.pluginList = (List<Export_to_Finance_Plugin__mdt>) JSON.deserialize(plugins, List<Export_to_Finance_Plugin__mdt>.class);
		Transaction_Export_Settings__mdt exportSettings;
 
        Test.startTest();
        List<PluginTest.IPluginTest> pluginList = PluginTest.getInstanceIPluginTest(exportSettings);
        System.assertEquals(2, pluginList.size());
        for(PluginTest.IPluginTest plugin : pluginList){
            System.assert(true, plugin.pluginTest(true));
        }

        List<Plugin.IETFBatchPreExecute> plugins2 = Plugin.getInstanceIETFBatchPreExecute();

        Test.stopTest();
    }

    /** PLUGIN TEST METHODS *
    private testMethod static void testGetInstanceIETFBatchPreExecute(){
        List<Plugin.IETFBatchPreExecute> plugins = Plugin.getInstanceIETFBatchPreExecute();
        System.assertEquals(1, plugins.size());
        System.debug('plugins - ' + plugins);
        System.assert(plugins.get(0) instanceof Plugin.IDefault); // Only the default should be returned
    }

    private testMethod static void testGetInstanceIETFBatchPreFinish(){
        List<Plugin.IETFBatchPreFinish> plugins = Plugin.getInstanceIETFBatchPreFinish();
        System.assertEquals(1, plugins.size());
        System.assert(plugins.get(0) instanceof Plugin.IDefault); // Only the default should be returned

    } */
}