objects/Gc_Log__c.object
<CustomObject>
    <description>This is a log that is used by batch processes and other parts of the system when errors or significant events occur</description>
    <fields>
        <fullName>Datetime__c</fullName>
        <description>Ths date and time that the log was raised</description>
        <inlineHelpText>Ths date and time that the log was raised</inlineHelpText>
        <label>Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <description>This is the type of error that occurred</description>
        <inlineHelpText>This is the type of error that occurred</inlineHelpText>
        <label>Error Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Full_Message__c</fullName>
        <description>This is the full log message</description>
        <inlineHelpText>This is the full log message</inlineHelpText>
        <label>Full Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <description>This is used to indicate if this log is just information or errors</description>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Log_Setting_Name__c</fullName>
        <description>This is the setting name that created this log. This can be used to group settings together for different operations</description>
        <inlineHelpText>This is the setting name that created this log. This can be used to group settings together for different operations</inlineHelpText>
        <label>Log Setting Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>This is the ID of the object that returned the error if that is known</description>
        <inlineHelpText>This is the ID of the object that returned the error if that is known</inlineHelpText>
        <label>Object Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>The name of the object if it is known</description>
        <inlineHelpText>The name of the object if it is known</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <description>A stack trace from the error if that is available</description>
        <inlineHelpText>A stack trace from the error if that is available</inlineHelpText>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>A short description of the log</description>
        <inlineHelpText>A short description of the log</inlineHelpText>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Gc_Log_Settings__mdt.object
<CustomObject>
    <description>This configures how various processes handle and log errors</description>
    <fields>
        <fullName>Error_Notification_Recipients__c</fullName>
        <description>The email addresses for the recipients of error notifications</description>
        <inlineHelpText>The email addresses for the recipients of error notifications</inlineHelpText>
        <label>Error Notification Recipients</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Notifications__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this if notification emails should be sent if an error is logged</description>
        <inlineHelpText>Check this if notification emails should be sent if an error is logged</inlineHelpText>
        <label>Error Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Log_Level__c</fullName>
        <defaultValue>&quot;Errors Only&quot;</defaultValue>
        <description>This is used to determine what sorts of logs should be stored</description>
        <label>Log Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Errors</fullName>
                    <default>true</default>
                    <label>Errors Only</label>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <description>If these logs should be linked to a particular record, then indicate the name of the lookup field on the log record that should be populated</description>
        <inlineHelpText>If these logs should be linked to a particular record, then indicate the name of the lookup field on the log record that should be populated</inlineHelpText>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Error_Logs__c</fullName>
        <description>This is the maximum number of error log records that will be created for this session</description>
        <inlineHelpText>This is the maximum number of error log records that will be created for this session</inlineHelpText>
        <label>Max Error Logs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Information_Logs__c</fullName>
        <description>This is the maximum number of information logs that should be generated for a session.</description>
        <inlineHelpText>This is the maximum number of information logs that should be generated for a session.</inlineHelpText>
        <label>Max Information Logs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rollback_Changes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this is checked then the code should attempt to roll back any changes. If tis is not checked then a partial commit may be possible</description>
        <inlineHelpText>If this is checked then the code should attempt to roll back any changes. If tis is not checked then a partial commit may be possible</inlineHelpText>
        <label>Rollback Changes</label>
        <type>Checkbox</type>
    </fields>
    <label>Log Settings</label>
    <pluralLabel>Log Settings</pluralLabel>
</CustomObject>

classes/Gc_LogService.cls
/**
 * @description This is used to create Log records
 * This implements the Singleton pattern so that only one is available per session
 * @author Eddie Bates
 * @date 22 January 2018
 * @copyright: Giveclarity.org, 2018
 **/
public with sharing class Gc_LogService {
	private static Gc_LogService instance = null; // This is the instance of this class to return each time the class is instantiated
	//public enum LogLevel {INFO, ERROR} // TODO
	private Integer errorLogCount = 0;
	private Integer infoLogCount = 0;
	private LogSettings oLogSettings;
	private List<Gc_Log__c> logs;
	private Id lookupObjectId;
	

	/**
	 * @description Make the constructor private to force the getInstance method to be used
	 * @param The name of the Log settings that this should use
	 * @param Id The Id of the Lookup Object
	 **/
	private Gc_LogService(String logSettingName, Id lookupObjectId) {
		this.oLogSettings = new LogSettings(logSettingName);
		this.lookupObjectId = lookupObjectId;
		if (logs == null) {
			logs = new List<Gc_Log__c>();	
		}
	}

	/**
	 * @description This either creates or finds a new instance of this service
	 * @param String The name of the settings that should be used
	 * @param Id The Id of the Lookup Object
	 **/
	public static Gc_LogService getInstance(String logSettingName, Id lookupObjectId) {
		if (instance == null) {
			instance = new Gc_LogService(logSettingName, lookupObjectId);
		}
		return instance;
	}

	/**
	 * @description This either creates or finds a new instance of this service
	 * @overload This overloads the main getinstance
	 **/
	public static Gc_LogService getInstance() {
		return getInstance(null,null);
	}

	/**
	 * @description This creates and returns a new Log object
	 * @param String The Subject
	 * @param String The Error Message
	 * @param Id The Object Id
	 * @return Gc_Log__c Returns the Log
	 **/
	public Gc_Log__c createInfoLog(String subjectStr, String fullMessage, Id objectId) {
		// Create a Log (this may not be saved)
		Gc_Log__c newLog = createLog('Information', 'Info: ' + subjectStr, fullMessage, objectId, null, null);

		// Check that the info Log count has not been exceeded
		if (this.oLogSettings.logLevel != 'Errors' && this.infoLogCount < this.oLogSettings.maxInfoLogs) {
			// Add the Log to the list
			logs.add(newLog);
		}

		// Returns the Logs, although info may not be saved or written to this
		this.infoLogCount++;
		return newLog;
	}

	/**
	 * @description This create and returns a new Log object
	 * @param String The type of Error
	 * @param String The Error Message
	 * @param Id The Object Id
	 * @param String The StackTrace message
	 * @return Gc_Log__c Returns the Log
	 **/
	public Gc_Log__c createErrorLog(String errorType, String fullMessage, Id objectId, String stackTrace) {
		// Create a Log (this may not be saved)
		Gc_Log__c newLog = createLog('Error', 'Error: ' + errorType, fullMessage, objectId, errorType, stackTrace);

		// Check that the info Log count has not been exceeded
		if (this.errorLogCount < this.oLogSettings.maxErrorLogs) {
			// Add the log to the list
			logs.add(newLog);
		}

		// Returns the Log, although info may not be saved or written to this
		this.errorLogCount ++;
		return newLog;

	}	

	/**
	 * @description When this is called any Logs that are in the list are written out. This can be used to avoid rollbacks
	 **/
	public void saveLogs() {

		if (logs.size() > 0) {
			insert logs;	

			// If notifications should be sent, then send thes out
			sendNotifications();

		}

		// Reset the logs list
		logs = new List<Gc_Log__c>();

	}


	/********************** PRIVATE METHODS *******************/
	private Gc_Log__c createLog(String logLevel, String subjectStr, String fullMessage, Id objectId, String errorType, String stackTrace) {
		Gc_Log__c newLog = new Gc_Log__c();
		newLog.Log_Level__c = logLevel;
		newLog.Log_Setting_Name__c = this.oLogSettings.settingsName;
		newLog.Datetime__c = System.now();
		newLog.Subject__c = subjectStr;
		newLog.Object_Id__c = objectId;
		newLog.Error_Type__c = errorType;
		newLog.Stack_Trace__c = stackTrace;
		newLog.Full_Message__c = fullMessage;
		
		// Set the lookup field if this is set
		if (this.lookupObjectId != null && this.oLogSettings.lookupFieldName != null) {
			// Wrap this in a try in case the field does not exist
			try {
				newLog.put(this.oLogSettings.lookupFieldName, this.lookupObjectId);
			} catch (Exception e) {
				// Do nothing 
				System.debug('Log Error: The lookup field name specified in the settings is not valid');
			}
		}		

		// If the Object Id has been supplied then record this
		if (objectId != null) {
			try {
				newLog.Object_Name__c = objectId.getSObjectType().getDescribe().getName();
			} catch (Exception e) {
				newLog.Object_Name__c = 'Invalid Object Id';
			}
		}

		return newLog;

	}

	private void sendNotifications() {

		// If notifications have been set then continue
		if (this.oLogSettings.sendNotifications == true) {
			// Loop through and send out notifications 


			// Update email sent on the logs


		}

	}

	/********************** INNER CLASS **********************/
	private class LogSettings {
		public String settingsName;
		public String notificationRecipients;
		public Boolean sendNotifications;
		public String logLevel;
		public String lookupFieldName;
		public Integer maxErrorLogs;
		public Integer maxInfoLogs;
		public Boolean rollbackChanges;

		/**
		 * @ddescription This either gets the settings or uses default values 
		 * @param String The name of the Log settings to retrieve
		 **/
		public LogSettings(String logSettingName) {
			// Set the default values
			this.sendNotifications = false;
			this.logLevel = 'Errors';
			this.maxErrorLogs = 10;
			this.maxInfoLogs = 10;
			this.rollbackChanges = true;

			// If settings have been specified then set them
			if (logSettingName != null) {
				// Use the setting name to find the meta data type for this setting
				List<Gc_Log_Settings__mdt> logSettingObjects = [SELECT Id, Error_Notification_Recipients__c, Error_Notifications__c, Log_Level__c, Lookup_Field_Name__c, Max_Error_Logs__c, 
																	Max_Information_Logs__c, Rollback_Changes__c
																		FROM Gc_Log_Settings__mdt
																		WHERE DeveloperName=:logSettingName];
				if (logSettingObjects.size() > 0) {
					this.settingsName = logSettingName;
					this.notificationRecipients = logSettingObjects[0].Error_Notification_Recipients__c;
					this.sendNotifications = logSettingObjects[0].Error_Notifications__c;
					this.logLevel = logSettingObjects[0].Log_Level__c;
					this.lookupFieldName = logSettingObjects[0].Lookup_Field_Name__c;
					this.maxErrorLogs = logSettingObjects[0].Max_Error_Logs__c == null ? 10 : (Integer)logSettingObjects[0].Max_Error_Logs__c;
					this.maxInfoLogs = logSettingObjects[0].Max_Information_Logs__c == null ? 10 : (Integer)logSettingObjects[0].Max_Information_Logs__c;
					this.rollbackChanges = logSettingObjects[0].Rollback_Changes__c;
				}

			}

		}

	}


}