objects/Transaction_Export_Settings__mdt.object
<CustomObject>
    <description>Finance Export: This defines a transaction export. It defines which object should be grouped and how records should be grouped</description>
    <fields>
        <fullName>Rollback_Batch_Size__c</fullName>
        <defaultValue>200</defaultValue>
        <description>This is the batch size used for the rollback process. This is the number of summary records that are processed and each of these links to multiple transactions. The lower the number the slower the process, but it can help avoid limits</description>
        <inlineHelpText>This is the batch size used for the rollback process. This is the number of summary records that are processed and each of these links to multiple transactions. The lower the number the slower the process, but it can help avoid limits</inlineHelpText>
        <label>Rollback Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Export Settings</label>
    <pluralLabel>Transaction Export Settings</pluralLabel>
</CustomObject>

objects/Transaction_Summary_Header__c.object
<CustomObject>
    <description>This is used to group together transaction summary records which are created for export to the finance system (VSA-33)</description>
    <fields>
        <fullName>Export_Name__c</fullName>
        <description>This is the name of the settings that have been used to generate these records (UUK-910)</description>
        <inlineHelpText>This is the name of the settings that have been used to generate these records</inlineHelpText>
        <label>Export Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction Summary Header</label>
    <nameField>
        <displayFormat>TSH-{0000000}</displayFormat>
        <label>Transaction Summary Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Summary Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GcFE_RollbackTransSummariesController.cls
/**
 * @description This supports the process which starts the rollback process
 * @author Eddie Bates
 * @date 22 January 2018
 * @copyright: Giveclarity.org, 2018
 **/
public with sharing class GcFE_RollbackTransSummariesController {

    /**
     * @description This calls the process to generate the file for this header
     **/
    @AuraEnabled
    public static void rollbackTransactionSummaries(Id transactionSummaryHeaderId) {

        // Start the process to export the transactions
        try {
            // Create a rollback class
            GcFE_TransactionSummaryRollbackBatch rollbackBatch = new GcFE_TransactionSummaryRollbackBatch(transactionSummaryHeaderId);

            // Get the header and therefore the settings
            Transaction_Summary_Header__c summaryHeader = [SELECT Id, Export_Name__c 
                                                           FROM Transaction_Summary_Header__c 
                                                           WHERE Id=:transactionSummaryHeaderId];
            Integer batchSize = null;
            if (summaryHeader.Export_Name__c != null) {
                Transaction_Export_Settings__mdt exportSettings = GcFE_TransactionSummaryService.getExportSettings(summaryHeader.Export_Name__c);
                batchSize = (Integer)exportSettings.Rollback_Batch_Size__c;
            }
            
            // Execute the batch
            if (batchSize != null) {
                Database.executeBatch(rollbackBatch, batchSize);    
            } else {
                Database.executeBatch(rollbackBatch);    
            }
            

        } catch (Exception e) {
            throw new AuraHandledException('Error Found: ' + e.getMessage());
        }
        
    }

    /**
	 * @description This calls the process to get the Transaction Summary Header Name
	 **/
    @AuraEnabled
    public static Transaction_Summary_Header__c getSummaryHeader(Id transactionSummaryHeaderId) {
        // Perform isAccessible() checks here
        return [SELECT Id, Name FROM Transaction_Summary_Header__c WHERE Id=:transactionSummaryHeaderId];
    }


}