objects/Transaction_Summary__c.object
<CustomObject>
    <description>This is a summary of transaction records. Each record becomes a row in the finance export file (VSA-33).</description>
    <fields>
        <fullName>Transaction_Summary_Header__c</fullName>
        <description>This is a link to the header record that represents an export (UUK-910)</description>
        <label>Transaction Summary Header</label>
        <referenceTo>Transaction_Summary_Header__c</referenceTo>
        <relationshipLabel>Transaction Summaries</relationshipLabel>
        <relationshipName>Transaction_Summaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction Summary</label>
    <nameField>
        <displayFormat>TS-{00000000}</displayFormat>
        <label>Transaction Summary ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transaction_Summary_Header__c.object
<CustomObject>
    <description>This is used to group together transaction summary records which are created for export to the finance system (VSA-33)</description>
    <fields>
        <fullName>Export_Name__c</fullName>
        <description>This is the name of the settings that have been used to generate these records (UUK-910)</description>
        <inlineHelpText>This is the name of the settings that have been used to generate these records</inlineHelpText>
        <label>Export Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This indicates whether this batch of summary records have posted to the finance system (UUK-910)</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Rolled Back</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Summary Header</label>
    <nameField>
        <displayFormat>TSH-{0000000}</displayFormat>
        <label>Transaction Summary Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Summary Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GcFE_TransactionSummaryRollbackBatch.cls
/**
 * @description Given a Summary Header ID this gets all the Summary records, 
 * resets the linked Transactions then removes the Summary records
 * @author Eddie Bates
 * @date 22 January 2018
 * @copyright: Giveclarity.org, 2018
 **/
global with sharing class GcFE_TransactionSummaryRollbackBatch implements Database.Batchable<sObject> {
	public Id headerId;
	public String query;
	public Integer errorCount;
	global Gc_LogService logService;	
	
	/**
	 * @description Given a Header ID this gets all the Transaction Summaries
	 * @param Id Summary Header Id
	 **/
	global GcFE_TransactionSummaryRollbackBatch(Id summaryHeaderId) {
		this.headerId = summaryHeaderId;

		// Set the error count to zero
		this.errorCount = 0;

		// Build up he query
//		query = 'SELECT Id FROM Transaction_Summary__c WHERE Transaction_Summary_Header__c=:headerId';

		query = GcFE_TransactionSummaryService.getRollbackTransactionQuery(summaryHeaderId);
		// Create a new Log Service
		this.logService = Gc_LogService.getInstance('GcFE_TransactionSummaryRollbackBatch', this.headerId);		

	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

    /**
	 * @description Call the process to create the Summary records
	 **/
   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		// Get the Summary Header object along with the export setting
		Transaction_Summary_Header__c summaryHeader = [SELECT Id, Status__c, Export_Name__c FROM Transaction_Summary_Header__c WHERE Id=:headerId];
   		
   		// Call the process to create the Summary records from the found objects
		GcFE_TransactionSummaryService.rollbackTransactionSummaries(scope, summaryHeader, logService);
	
	}
	
    /**
	 * @description Update the Status of the Transaction Summary Header to 'Rolled Back'
	 **/
	global void finish(Database.BatchableContext BC) {

		// Change the status of the Header record to 'Rolled Back'
		Transaction_Summary_Header__c summaryHeader = [SELECT Id, Status__c FROM Transaction_Summary_Header__c WHERE Id=:headerId];
		summaryHeader.Status__c = 'Rolled Back';
		update summaryHeader;
		
		List<sObject> transactionSummaryObjs = [SELECT Id FROM Transaction_Summary__c WHERE Transaction_Summary_Header__c=:headerId];
		delete transactionSummaryObjs;
	}
	
}